const generateFinal = printTeam => {


  const generateManager = manager => {
    return ` <div class="card small">
    <div class="card-image waves-effect waves-block waves-light">
      <img class="activator" src="./images/office.jpg">
    </div>
    <div class="card-content">
      <span class="card-title activator grey-text text-darken-4"><i class="material-icons">folder_shared</i>${manager.getRole()} : ${manager.getName()}  <i class="material-icons right">more_vert</i></span>
    </div>
    <div class="card-reveal">
      <span class="card-title grey-text text-darken-4">${manager.getName()}<i class="material-icons right">close</i></span>
      <ul>
      <li> Employee ID: ${manager.getID()} </li>
      <li> Email: <a href="mailto:${manager.getEmail()}">${manager.getEmail()}</a></li>
      <li>Office number: ${manager.getOffice()}</li>
      </ul>
    </div>
   </div>
    
    `;
  };

  const generateEngineer = engineer => {
    return `<div class="card small">
    <div class="card-image waves-effect waves-block waves-light">
      <img class="activator" src="./images/coding.jpg">
    </div>
    <div class="card-content">
      <span class="card-title activator grey-text text-darken-4"><i class="material-icons">developer_mode</i>${engineer.getRole()} : ${engineer.getName()} <i class="material-icons right">more_vert</i></span>
    </div>
    <div class="card-reveal">
      <span class="card-title grey-text text-darken-4">${engineer.getName()}<i class="material-icons right">close</i></span>
      <ul>
      <li>Employee ID: ${engineer.getID()}</li>
      <li> Email: <a href="mailto:${engineer.getEmail()}">${engineer.getEmail()}</a></li>
      <li> <a href="https://github.com/${engineer.getGithub()}">Github</a></li>

      
      </ul>
    </div>
   </div>`;
  };

  

  const generateIntern = intern => {

    return `<div class="card small">
    <div class="card-image waves-effect waves-block waves-light">
      <img class="activator" src="./images/study.jpg">
    </div>
    <div class="card-content">
      <span class="card-title activator grey-text text-darken-4"><i class="material-icons">book</i>${intern.getRole()} : ${intern.getName()}<i class="material-icons right">more_vert</i></span>
    </div>
    <div class="card-reveal">
      <span class="card-title grey-text text-darken-4">${intern.getName()}<i class="material-icons right">close</i></span>
      <ul>
      <li>Employee ID: ${intern.getID()}</li>
      <li>Email: <a href="mailto:${intern.getEmail()}">${intern.getEmail()}</a></li>
      <li>School: ${intern.getSchool()}</li>
      </ul>
    </div>
   </div>`;
  };

  //empty array of cards to be generated by the generate team functions
  const cards = [];


  //function to check if each new array is unique and map any duplicate employees into cards array for respective classes
    cards.push(printTeam
        .filter(employee => employee.getRole() === "Manager")
        .map(manager => generateManager(manager))
    );
    cards.push(printTeam
        .filter(employee => employee.getRole() === "Engineer")
        .map(engineer => generateEngineer(engineer))
        .join("")
    );
    cards.push(printTeam
        .filter(employee => employee.getRole() === "Intern")
        .map(intern => generateIntern(intern))
        .join("")
    );

    return cards.join("");

    

};

module.exports = printTeam => {

 return `
 
 <!DOCTYPE html>
<html lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, maximum-scale=1.0"
    />
    <title>Team Members</title>
    <link
      href="https://fonts.googleapis.com/icon?family=Material+Icons"
      rel="stylesheet"
    />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css"
    />
  </head>
  <body>
    <nav class="light-blue lighten-1" role="navigation">
      <div class="nav-wrapper container">
        <a id="logo-container" href="#" class="brand-logo">Our Team</a>
        <ul class="right hide-on-med-and-down"></ul>

        <ul id="nav-mobile" class="sidenav"></ul>
        <a href="#" data-target="nav-mobile" class="sidenav-trigger"
          ><i class="material-icons">menu</i></a
        >
      </div>
    </nav>
    <div class="section no-pad-bot" id="index-banner">
      <div class="container">
        <br /><br />
        <h1 class="header center orange-text">Team Profile Generator</h1>
        <div class="row center">${generateFinal(printTeam)}</div>
        <br /><br />
      </div>
    </div>

    

    <div class="container">
      <div class="section">
        <!--   Icon Section   -->
        <div class="row">
          <div class="col s12 m4">
            <div class="icon-block">
              <h2 class="center light-blue-text">
                
              </h2>
              <h5 class="center"></h5>

              <p class="light"></p>
            </div>
          </div>

          <div class="col s12 m4">
            <div class="icon-block">
              <h2 class="center light-blue-text">
               
              </h2>
              <h5 class="center"></h5>

              <p class="light"></p>
            </div>
          </div>

          <div class="col s12 m4">
            <div class="icon-block">
              <h2 class="center light-blue-text">
               
              </h2>
              <h5 class="center"></h5>

              <p class="light"></p>
            </div>
          </div>
        </div>
      </div>
      <br /><br />
    </div>

    <footer class="page-footer blue">
      <div class="container">
        <div class="row">
          <div class="col l6 s12">
            <h5 class="white-text">Company Bio</h5>
            <p class="grey-text text-lighten-4">
              This is a fake company of the best employees
            </p>
          </div>
          <div class="col l3 s12"></div>
        </div>
      </div>
      <div class="footer-copyright">
        <div class="container">
          Made by
          <a
            class="grey-text text-lighten-3"
            href="https://github.com/jgault87"
            >JJ Gault</a
          >
        </div>
      </div>
    </footer>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
  </body>
</html>

 
 `   
}